namespace NDDDSample.Domain.Model.Cargos
{
    using Infrastructure.Validations;
    using Shared;

    /// <summary>
    /// Uniquely identifies a particular cargo. Automatically generated by the application.
    /// </summary>
    public class TrackingId : ValueObject<TrackingId>
    {
        public string ID { get; private set; }

        /// <summary>
        /// Constructor.
        /// </summary>
        /// <param name="id"></param>
        public TrackingId(string id)
        {
            Validate.NotNull(id);
            ID = id;

            RegisterProperty(p => p.ID);
        }
    }
}